project:
  type: website

website:
  title: "DS学习博客"
  bread-crumbs: true
  back-to-top-navigation: true
  page-footer: "© Huiyu 2024"
  reader-mode: true
  repo-url: https://github.com/BrotherJiang/blogs
  repo-actions: [edit, issue]

  navbar:
    background: primary
    foreground: light
    pinned: true
    search: true
    left:
      - text: "首页"
        href: index.qmd
      - text: "个人简介"
        href: about.qmd
      - sidebar:causal
      # - sidebar:ai

  sidebar:
    - id: causal
      title: "因果推断"
      style: "docked"
      background: light
      collapse-level: 2
      contents: "posts/Causal-Inference/*.qmd"
    
    # - id: ai
    #   title: "AI新闻"
    #   contents: "posts/AI-news/*.qmd"
      
format:
  html:
    lang: zh-CN  # 设置网页语言为中文
    date-locale: zh_CN
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
