project:
  type: website

website:
  title: "Huiyu的DS学习博客"
  bread-crumbs: true
  back-to-top-navigation: true
  page-footer: "© Huiyu Jiang 2024"
  reader-mode: true
  repo-url: https://github.com/BrotherJiang/blogs
  repo-actions: [edit, issue]

  navbar:
    background: primary
    foreground: light
    pinned: true
    search: true
    left:
      - text: "博客"
        file: index.qmd
      - text: "个人简介"
        file: about.qmd
    # right:
    #   - icon: github
    #     menu:
    #     - text: Source Code
    #       url: https://code.com
    #     - text: Report a Bug
    #       url: https://bugs.com
    #   - icon: twitter
    #     href: https://twitter.com
    #   - icon: google
    #     href: http://google.com/

  sidebar:
    - title: "学习系列"
      style: docked
      type: dark
      background: light
      contents: auto
    #     - text: "Causal Inference"
    #       href: posts/Causal-Inference/index.qmd  # Ensure you have an index.qmd for listing series posts
    #     - text: "AI News"
    #       href: posts/AI-news/index.qmd
    # - title: "其他链接"
    #   contents:
    #     - references.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css