---
title: "线上实验三：补充及替代技法"
date: "2024-05-30"
keywords: ["回顾性分析", "观察性因果研究"]
series: "Causal-Inference"
---

本文是《Trustworthy Online Controlled Experiments》（中文版《关键迭代：可信赖的线上对照试验》）的第三部分（10-11章）主要内容的总结。


# 第10章：补充技法

对于实施成本高的实验创意，可以使用补充技法进行早期评估和筛选，从而精简创意以减少实现成本。

### 1. 基于日志的分析（回顾性分析）

运行可信赖的A／B实验的一个先决条件是正确地通过日志记录用户测览、动作和互动，以计算评估对照实验的指标。

- **建立直觉**：定义和理解指标的分布及其随时间变化，帮助了解产品基准线和用户行为差异。
- **刻画潜在指标**：理解新指标与现有指标的相关性和分布，评估其在决策中的有用性。
- **基于数据探索生成A/B实验创意**：识别用户流失点，以改进产品功能或用户界面设计。
- **评估创意可行性**：分析数据确定创意的影响大小，决定是否进行A/B实验。
- **自然实验**：利用外生环境变化或系统漏洞进行观察性分析，测量其效果。
- **观察性因果研究**：在实验不可行时使用准实验设计结合实验数据，获得更准确的推断。

日志分析可补充A/B实验，但其局限在于只能基于过去的数据推断未来。因此，需结合用户和市场调研提供更全面的视角。


### 2. 人工评估

人工评估是指公司雇佣评估员完成某些任务，将结果用于后续分析。局限性包括数据质量可能参差不齐、评估者需要被训练来反映真实用户体验。所以这类数据需要校准。

基于人工评估的指标可以当作评估A／B实验的额外指标。人工评估还可用于调试，帮助查明改动表现好坏。将其与日志分析结合，可更好理解用户行为与结果的关系。

### 3. 用户体验调研（UER）

用户体验调研通过观察少数用户，收集日志无法获得的数据，生成指标创意。但需通过大规模方法验证这些创意。


### 4. 焦点小组

焦点小组通过有引导的小组讨论收集数据。相比于用户体验调研更易规模化，但覆盖内容有限，易受群体性思维影响，适用于产品设计早期阶段理解情绪反应。


### 5. 问卷调查

问卷调查通过招募用户回答问题收集数据。设计时要注意避免误导或引导答案，用户自我报告可能不完全真实，且调查样本易有偏差。

但问卷调查能够接触更多用户，得到工具化数据外的信息，对用于观测难以直接测量的问题随时间变化的趋势有帮助。

### 6. 外部数据

外部数据由第三方收集，来源包括：站点级别数据、用户级别数据、问卷调查结果、学术论文， 以及经验教训。

外部数据可用于：

- 验证业务指标，如查看内部和外部数据的时间序列以比较趋势。
- 学术论文可以确立指标间的对等关系。
- 公司可以借助外部研究结果确定大方向和投资策略。
- 外部数据还提供竞争性研究，为内部业务数据提供基准。

尽管外部数据的绝对数字可能不完全可靠，但在趋势分析、相关性研究和指标验证方面非常有用。

# 第11章：观察性因果研究
因果推断的基本等式：
\begin{align*}
&\text{受影响人群的结果（treated）} - \text{未受影响人群的结果（untreated） } \\
=&\left(\text{受影响人群的结果（实际影响）} - \text{受影响人群如果未受影响的结果（虚拟事实）}\right) \\
&+ \left(\text{受影响人群如果未受影响的结果} - \text{未受影响人群的结果}\right) \\
= &\text{变动对于受影响人群的作用} + \text{选择性偏差}
\end{align*}

对照实验是评估因果关系的黄金标准，因为当实验单元被随机分配到不同变体时，该等式第一项即为对照组与实验组间观测到的差别，而第二项的期望值为零。

### 1. 对照实验不可行的情况
在以下情况下，可能无法进行对照实验：

- 想要测试的可能有因果效应的行为不受这个机构控制;
- 样本单位太少；
- 建立对照组的机会成本过高；
- 变动的成本相对于预期价值过高；
- 想要的随机化单元无法适当地随机分配；
- 测试内容不道德或非法。

在这些情况下，可以考虑进行观察性因果研究或第10章介绍的其他补充技法。

### 2. 观察性因果研究的设计
观察性因果研究中的难点包括：

- 如何构建可以比较的对照组和实验组；
- 给定对照组和实验组，如何建模以估计影响。

#### 中断时间序列（ITS）
中断时间序列（Interrupted Time Series）是一种准实验设计，你可以控制系统中的变动，但不能通过随机分配变动来构建真正的对照组和实验组。作为替代，用同样的用户群作对照组和实验组，并随时间改变用户群的体验。

具体而言，在变动介人之前，它使用不同时间的多次测量来创建一个模型，该模型可以估计变动介人后的相关指标————虚拟事实。变动后，再进行多次测量，并将关注指标的实际值与模型的预测值之间的平均差作为实验效应的估计。一个简单扩展是引入实验变动然后将其反转，并可以选择多次重复此过程。

观测因果研究的一个常见问题是如何确保在实际上有混杂效应的时候不会把影响错误的归因于实验变动。最常见的混杂因素是时间效应，如季节性。来回进行多次实验变动有助于降低这种可能性。另一个要考虑的因素是用户体验，避免来回变化降低用户满意度。

#### 交错式实验
交错式实验设计常用于评估排名算法的变化，其适用性有限，因为结果必须是同质的。如果某个结果占用更多空间或影响页面其他区域，会增加实验复杂性。

#### 断点回归设计（RDD）
断点回归设计（Regression Discontinuity Design）适用于受实验影响的人群由明确阈值识别的情况。基于阈值，我们将刚好低于阈值的人群作为对照组，刚好高于阈值的人群作为实验组，通过比较两组来减少选择性偏差。注意在阈值处的实验断点可能会受到共享同一阈值的其他因素的污染。

#### 工具变量（IV）和自然实验
工具变量（Instrumented Variable）技术尝试近似随机分配。目标是找到一个工具变量，使我们能够近似随机分配（这在自然实验中自然发生）。

#### 倾向评分匹配（PSM）
倾向评分匹配（Propensity Score Matching）是一种用于构造可比较的对照组和实验组的方法。通过考虑常见的混杂因素对用户进行细分，类似于分层抽样，确保对照组和实验组之间的差异不是由于人群结构的变化。

PSM通过将单元按构造的倾向评分（而非协变量）进行匹配。PSM的关键问题是它仅考虑可观察到的协变量，而未考虑的因素可能导致潜在的偏差。

#### 双重差分法（DID）

双重差分法（Difference-in-Differences）用于测量实验效应。该方法假设对照组和实验组在趋势上是相同的，并将趋势变化的差异归因于实验效果。特别是在没有实验变动的情况下，对照组和实验组的指标数值可能有所不同，但只会平行移动。

基于地理位置的实验通常使用这种方法。假设对照组在不同时间点的指标差异捕捉了外部因素（如季节性、经济状况）的影响，那么这个差异提供了实验组在没有变动情况下的虚拟事实。实验效应可以通过实验组相关指标的变化与对照组同期变化之差来估计。即
$$
\text{实验效应} = \left(M_{\text{实验组}，T_2} - M_{\text{实验组}，T_1}\right) - \left(M_{\text{对照组}，T_2} - M_{\text{对照组}，T_1}\right)
$$
这里$M_{\text{实验组}，T_2}$表示实验组在时间$T_2$时得到的指标值。

这种方法也适用于测量外生性变化的情况。

### 3. 陷阱
观察性因果研究的主要陷饼是未考虑到的混杂因素，一种常见类型是未识别的共同原因。另一个陷阱是伪相关性或欺骗性的相关性（由大的离群值引起）。

### 参考文献

- Kohavi, Ron, Diane Tang, and Ya Xu. *Trustworthy Online Controlled Experiments: A Practical Guide to A/B Testing (关键迭代：可信赖的线上对照试验)*. Cambridge University Press, 2020.

### 留言区
欢迎在下方留言讨论。如果您无法输入评论，请确保您已登录 GitHub 账号。

{{< include ../../_includes/utterances.html >}}